# Generated by Django 2.2 on 2020-09-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='There are no notes here.', max_length=255),
        ),
    ]
