# Generated by Django 2.2 on 2020-09-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='release_date',
            field=models.CharField(default='01/01/2020', max_length=10),
        ),
    ]
